Shared content stat
fivejars/openy_gated_content pull request #106
Opened 2020-09-16 12:33 UTC by anpolimus

Steps for reproduce:
1. - [ ] Enable shared content server module at one of the builds. Make all content available to share at `admin/content` page
2. - [ ] Add the first server as a source server instead of shared.openy at: `admin/virtual-y/shared-content/server/add`
3. - [ ] Open fetch form at the second server and try to download content to your local Virtual Y
4. - [ ] Verify that count of downloads increased after successful download at the first server reporting page: `/admin/virtyal-y/shared-content/download-stat`
5. - [ ] Verify that count of downloads updated at the fetch form.
6. - [ ] Check filters and ability to export in csv at the first server reporting page.

2020-09-16 15:00 UTC, hamrant requested changes

2020-09-16 15:01 UTC, anpolimus commented on modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYBlogPost.php
> +      'include' => 'field_vy_blog_image,field_vy_blog_image.field_media_image, field_share_count, field_gc_origin',
Ah yes, you are right

2020-09-16 15:02 UTC, anpolimus commented on modules/openy_gc_shared_content_server/openy_gc_shared_content_server.routing.yml
> +    _permission: 'access content'
Token now checks inside of the post

2020-09-16 15:03 UTC, hamrant commented on modules/openy_gc_shared_content_server/openy_gc_shared_content_server.routing.yml
> +    _permission: 'access content'
ok, I see

2020-09-16 15:04 UTC, anpolimus commented on modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
> +          'url' => 'http://openy.docksal',
already :)

2020-09-17 12:34 UTC, anpolimus commented on modules/openy_gc_shared_content_server/config/install/views.view.virtual_y_shared_content_statistic.yml
> +          perm: 'access content'
updated

2020-09-17 13:42 UTC, hamrant requested changes
```
Unable to install Open Y Virtual Y shared content server due to unmet dependencies: views.view.virtual_y_shared_content_statistic (csv_serialization, views_data_export)
```

Error on module enabling (looks like we need this dependencies on module level)

2020-09-17 19:24 UTC, anpolimus commented
retest

2020-09-18 14:04 UTC, hamrant approved these changes

2020-09-18 14:05 UTC, merged