Users rebuild preparation
fivejars/openy_gated_content pull request #110
Opened 2020-09-22 09:42 UTC by anpolimus

2020-09-23 15:42 UTC, hamrant approved these changes

2020-09-23 15:43 UTC, hamrant commented
The code looks ok for me, there will be small conflicts with my PR

2020-09-24 08:36 UTC, jediandrey commented
retest

2020-09-24 09:20 UTC, hamrant requested changes

2020-09-24 09:20 UTC, hamrant commented on js/gated-content/src/store/index.js
>      authCustom,
I think we can delete authCustom too

```
import authCustom from './modules/auth/custom';
```

2020-09-24 09:20 UTC, hamrant commented on src/Form/GCSettingsForm.php
> +    $settings->set('event_add_to_calendar', $form_state->getValue('event_add_to_calendar'));
Please remove these lines, no need to set params separately, they already in `app_settings`

2020-09-24 09:26 UTC, hamrant commented
Events not available for dummy user: 
![Screenshot from 2020-09-24 12-21-47](https://user-images.githubusercontent.com/13733670/94126700-9ba7c380-fe60-11ea-9c90-1f0662c9411e.png)

Dummy User can click on `My account` link in the main menu and see `/user` page:

![Screenshot from 2020-09-24 12-24-27](https://user-images.githubusercontent.com/13733670/94126942-f3dec580-fe60-11ea-8e6b-346559c6e7c2.png)

And can access the user edit page:

![Screenshot from 2020-09-24 12-24-37](https://user-images.githubusercontent.com/13733670/94126968-fccf9700-fe60-11ea-932e-a00250a05e4d.png)

I think we need to close access to these pages for virtual y roles too.

2020-09-24 10:00 UTC, hamrant approved these changes
@jediandrey please fix comments in separated PR

2020-09-24 10:00 UTC, merged