YOPN-927 VY: Rebuild user and node logging completely
fivejars/openy_gated_content pull request #115
Opened 2020-09-25 11:29 UTC by jediandrey

2020-09-25 11:45 UTC, anpolimus requested changes

2020-09-25 11:45 UTC, anpolimus commented on modules/openy_gc_auth/openy_gc_auth.info.yml
> +dependencies:
It should work only if user enabled this module.
We have to keep everything working if openy_gc_log was disabled.

2020-09-28 09:17 UTC, hamrant commented
retest

2020-09-28 09:20 UTC, hamrant approved these changes
**TODO** for @hamrant: add the same log for CSV auth

2020-09-28 10:01 UTC, hamrant commented
Tested, with disabled module works fine, with enabled no any issues or errors:

![Screenshot from 2020-09-28 12-59-27](https://user-images.githubusercontent.com/13733670/94418808-901f0a00-018a-11eb-9f84-e5c517dbe1b8.png)

No regressions logs work as expected.

2020-09-28 10:01 UTC, merged