VY: Make logout link configurable
fivejars/openy_gated_content pull request #135
Opened 2020-10-12 13:53 UTC by jediandrey

2020-10-13 09:08 UTC, anpolimus approved these changes

2020-10-13 09:09 UTC, anpolimus commented
Code is ok, please rebuild app and fix merge conflict

2020-10-13 09:29 UTC, hamrant requested changes

2020-10-13 09:29 UTC, hamrant commented on openy_gated_content.module
> +  $variables['#attached']['drupalSettings']['openy_gated_content']['logoutUrl'] = !empty($app_config['virtual_y_logout_url']) ? $app_config['virtual_y_logout_url'] : base_path() . 'user/logout';
No need to add this to `drupalSettings`, config already exists in `$variables['app_settings']`.

Example how to get this setting in component:

```js
  computed: {
    ...mapGetters([
      'getAppSettings',
    ]),
  },

```

or

```js
    logoutUrl() {
      return this.$store.getters.getAppSettings.virtual_y_logout_url;
    },
```

or use `SettingsMixin` that already includes second example

2020-10-13 09:29 UTC, hamrant commented on js/gated-content/src/components/LogoutLink.vue
> +  data() {
Please use `SettingsMixin`, example:

```js
import { SettingsMixin } from '@/mixins/SettingsMixin';

export default {
  name: 'BlogListing',
  mixins: [SettingsMixin],
  computed: {
    logoutUrl() {
      return this.config.virtual_y_logout_url;
    },
  },

```

2020-10-13 09:29 UTC, hamrant commented on config/install/openy_gated_content.settings.yml
> +virtual_y_logout_url: /user/logout
We need a hook update that will set only this value for existing projects

2020-10-13 09:29 UTC, hamrant commented on config/install/openy_gated_content.settings.yml
> +virtual_y_logout_url: /user/logout
Please update `openy_gated_content.schema.yml` too

2020-10-15 13:10 UTC, anpolimus approved these changes

2020-10-15 13:10 UTC, merged