VY: various bugfixes
fivejars/openy_gated_content pull request #150
Opened 2020-10-23 14:51 UTC by jediandrey

2020-10-24 20:46 UTC, anpolimus requested changes

2020-10-24 20:46 UTC, anpolimus commented on openy_gated_content.install
> +  $schema['eventseries_field_data']['fields']['field_vy_permission']['length'] = 255;
I think, we have to add length value to the hook_install as well.
@jediandrey

2020-10-26 20:47 UTC, anpolimus commented on modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Plugin/GCIdentityProvider/YUSA.php
> +        $this->t('You must disable "Email verification" when "Verification Type" is set to "Membership ID or Barcode".'
```suggestion
        $this->t('You must disable "Email verification" when "Verification Type" is set to "Membership ID" or "Barcode". Virtual Y is unable to send a verification email if user email is not used and stored as the "Verification Type" for login.'
```

2020-10-27 13:04 UTC, hamrant approved these changes

2020-10-27 14:33 UTC, anpolimus approved these changes

2020-10-27 14:39 UTC, anpolimus commented
Code was tested. Ready tomerge.

2020-10-27 14:39 UTC, merged