Fix for page layout fix for blog posts without image.
fivejars/openy_gated_content pull request #166
Opened 2020-11-11 17:12 UTC by bharath-kondeti

2020-11-12 14:25 UTC, froboy requested changes
@bharath-kondeti a few questions/comments here. Also, please run `npm run build` and commit the resulting files into this branch.

2020-11-12 14:25 UTC, froboy commented on js/gated-content/src/views/BlogPage.vue
> +      <div v-if="blog.attributes.field_vy_blog_image !== null">
@bharath-kondeti is it possible to put this `v-if` on the div below so we're not creating unnecessary divs?

So, something like `<div class="blog-page__image" v-if="blog.attributes.field_vy_blog_image !== null" v-bind:...`

2020-11-12 14:25 UTC, froboy commented on js/gated-content/src/views/BlogPage.vue
> +      <div v-else><div class="blog-page__no-image"></div></div>
Why is an empty div needed here? I tested on the sandbox and `div.blog-page__image` being gone seems sufficient to fix the formatting.

2020-11-16 14:44 UTC, froboy commented
@bharath-kondeti thanks for the update. This is much cleaner now. Either I or one of the Open Y team will need to test, merge in the latest, and then regenerate the compiled `js`.

2020-11-18 12:08 UTC, anpolimus commented
@bharath-kondeti may I ask you to rebuild app against the last master?
Code is ok but we have to fix merge conflict first.

2020-11-18 17:59 UTC, bharath-kondeti commented
@anpolimus I have worked on the merge conflicts. Please verify the same.

2020-11-19 14:13 UTC, anpolimus commented
Ok thx

2020-11-20 09:43 UTC, hamrant submitted a review, later dismissed

2020-11-20 17:14 UTC, hamrant commented
@bharath-kondeti may I ask you to rebuild app one more time?

2020-11-23 05:31 UTC, bharath-kondeti commented
@hamrant, I will do that.

2020-11-24 10:23 UTC, podarok requested changes

2020-11-24 10:23 UTC, podarok commented on modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/config/openy_gc_auth.provider.daxko_sso.yml
> +redirect_url: '/openy-gc-auth-daxko-sso/back-redirect'
upgrade path needed

2020-11-24 13:25 UTC, anpolimus approved these changes

2020-11-24 13:25 UTC, merged