R1.2 - Personify SSO - Issue #52: Add Login form and options to redirect
fivejars/openy_gated_content pull request #167
Opened 2020-11-13 12:34 UTC by jediandrey

1) Choose Personify provider as Auth method
2) go to / virtual-ymca
3) ensure you're not redirecting immediately to Personify login form but see "Enter virtual y" button
4) click on it and finish login process

2020-11-17 14:23 UTC, anpolimus approved these changes

2020-11-17 14:23 UTC, anpolimus commented
Code is ok.

2020-11-18 09:18 UTC, hamrant requested changes

2020-11-18 09:18 UTC, hamrant commented on modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Form/VirtualYPersonifyLoginForm.php
> +  public function __construct() {}
Can we remove `__construct` and `create` functions?

2020-11-18 20:35 UTC, froboy commented
@jediandrey @hamrant @anpolimus is the same change for Daxko SSO in the works on a different ticket, or could that be added here?

2020-11-20 09:36 UTC, hamrant approved these changes

2020-11-20 09:41 UTC, merged