VY: Add Autologout functionality
fivejars/openy_gated_content pull request #171
Opened 2020-11-17 12:31 UTC by jediandrey

2020-11-17 12:42 UTC, jediandrey commented
retest

2020-11-18 11:14 UTC, anpolimus requested changes

2020-11-18 11:14 UTC, anpolimus commented on modules/openy_gc_autologout/openy_gc_autologout.module
> +  $result = $connection->select('paragraphs_item_field_data', 'pd')
I think it is good chance to make a separate service for this code and for existed one:
https://github.com/fivejars/openy_gated_content/blob/master/modules/openy_gc_auth/src/EventSubscriber/VirtualYLoginRedirect.php#L155

2020-11-18 11:19 UTC, hamrant requested changes

2020-11-18 11:19 UTC, hamrant commented on modules/openy_gc_autologout/openy_gc_autologout.module
> +    ->fetchAll();
Let's add some limit here

2020-11-19 14:30 UTC, anpolimus approved these changes

2020-11-19 14:30 UTC, anpolimus commented
Code is ok.

2020-11-19 14:31 UTC, hamrant approved these changes

2020-11-19 15:52 UTC, NadyaRudenko commented
@jediandrey , tested on Safari. 
I was not logged out
When I set a new time at /admin/virtual-y/openy-gc-autologout and click 'Save configuration', I can see the default time again. I'm not sure if this is right
![image](https://user-images.githubusercontent.com/62060358/99689549-c9d80700-2a8f-11eb-827a-4b0dbdfe2490.png)

2020-11-20 12:46 UTC, jediandrey commented
@NadyaRudenko fixed, please try again

2020-11-20 14:36 UTC, NadyaRudenko commented
Retested, fixed. Thank you!

2020-11-20 17:10 UTC, hamrant approved these changes

2020-11-20 17:11 UTC, merged