Add PR template
fivejars/openy_gated_content pull request #180
Opened 2020-11-30 16:49 UTC by froboy

**Related Issue/Ticket:**

No issue. I know https://github.com/ymcatwincities/openy/blob/8.x-2.x/.github/PULL_REQUEST_TEMPLATE.md exists, but I thought we could use something a little smaller here.

## To Test:

- [ ] Merge this PR
- [ ] Create a new PR
- [ ] Check out the great template!

2020-11-30 16:55 UTC, podarok submitted a review, later dismissed

2020-12-01 09:15 UTC, hamrant submitted a review, later dismissed

2020-12-01 11:14 UTC, anpolimus requested changes
@froboy thank you for this PR. We really need this!
Since we've focused on it, lets make the template complete:
- please add upgrade path section
  We have to inform the developer that the upgrade path for the existed project is very important
- we have to add note that for frontend fixes it should be tested across all 3 themes: Rose, Lily, Carnation
- please add section and inform developer that he/she should add Need review tag to start review.

2020-12-01 11:14 UTC, anpolimus commented on .github/pull_request_template.md
> +## To Test:
```suggestion
## Steps to test:
```

2020-12-03 14:19 UTC, froboy commented
@anpolimus I modified your suggestion a little, as only the Open Y team has privileges to add tags here, but based on my conversations with the team, it sounds like anyone outside of OY/5J/IX who makes PRs should be notifying folks in Slack, so I added that.

2020-12-03 14:23 UTC, hamrant approved these changes

2020-12-03 14:34 UTC, anpolimus approved these changes

2020-12-03 14:34 UTC, anpolimus commented
Thank you! Now, our template looks amazing!

2020-12-03 14:34 UTC, merged