Updated vylogs from mini pager to full pager.
fivejars/openy_gated_content pull request #185
Opened 2020-12-04 13:51 UTC by bharath-kondeti

**Related Issue/Ticket:**

https://github.com/ymcatwincities/openy_gated_content/issues/72

## Steps to test:

- [ ] Take a git pull
- [ ] Then run drush updb -y
- [ ] Then check the pager will be updated to full in the place of mini.

2020-12-04 14:17 UTC, froboy requested changes
@bharath-kondeti I've reviewed and the functionality looks good, but I've noted a few requested changes in the code.
![Virtual_Y_Logs___Open_Y_Sandbox_-_carnation](https://user-images.githubusercontent.com/238201/101174037-f439d080-3608-11eb-90c6-6292243d36e4.png)

Also, please update your testing instructions based on testing from the builds that are generated above. I had to first enable the log module then log in and hit a number of pages as a member in order to test the new functionality.

Thanks!

2020-12-04 14:17 UTC, froboy commented on modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
> +uuid: 9e78fd87-e8b0-44e6-9621-88c3b895b38f
UUID should not be in exported config.

2020-12-04 14:17 UTC, froboy commented on modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
> -                title: videoPlaybackStarted
It looks like these lines might have been unintentionally removed.

2020-12-04 14:17 UTC, froboy commented on modules/openy_gc_log/openy_gc_log.install
> + * Update logs view.
Great!

2020-12-05 13:49 UTC, froboy approved these changes
Looks good to me. Thanks!

2020-12-07 13:21 UTC, anpolimus commented
@bharath-kondeti thank you for upgrade path!
Approved, sending to QA.

2020-12-09 14:47 UTC, NadyaRudenko commented
retest

2020-12-09 15:33 UTC, NadyaRudenko commented
Tested, all good, thanks

2020-12-09 15:34 UTC, merged