Add null checks for entity on log archiver.
fivejars/openy_gated_content pull request #239
Opened 2021-01-14 14:23 UTC by froboy

**Related Issue/Ticket:**

Resolves https://github.com/ymcatwincities/openy_gated_content/issues/96

## Steps to test:

- [ ] Enable the VY log module
- [ ] Create some recurring Live Streams/Virtual Meetings
- [ ] View those nodes through VY
- [ ] Change the recurrence so that those nodes are deleted from the db
- [ ] Run a log export and see that it completes successfully.

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [x] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [x] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

2021-01-14 15:44 UTC, hamrant approved these changes
Code looks ok

2021-01-14 15:58 UTC, hamrant commented
@froboy tested on build works fine.

I think it better to use an early return pattern, because above we already have predefined row values:

```php
      $export_row = [
        'created' => date('m/d/Y - H:i:s', $log->get('created')->value),
        'user' => $log->get('uid')->target_id ? $log->get('uid')->entity->getEmail() : '',
        'event_type' => $event_type,
        'entity_type' => $entity_type,
        'entity_bundle' => $entity_bundle,
        'entity_id' => $entity_id,
        'entity_title' => '',
        'entity_instructor_name' => '',
        'entity_created' => '',
      ];

...

        $entity = $this->entityTypeManager->getStorage($entity_type_id)
          ->load($entity_id);

        if (!$entity) {
          continue;
        }

```

2021-01-14 16:09 UTC, froboy commented
@hamrant that's quite elegant. I haven't used `continue` very much, so I appreciate the suggestion. Updated.

2021-01-14 16:10 UTC, anpolimus requested changes

2021-01-14 16:10 UTC, anpolimus commented on modules/openy_gc_log/src/LogArchiver.php
> +        if ($entity) {
@froboy , @hamrant we need something like this in this place:
```suggestion
        if ($entity is not instanceof EntityInterface) {
```

2021-01-14 16:12 UTC, hamrant commented
retest

2021-01-14 16:14 UTC, hamrant commented
retest

2021-01-14 16:16 UTC, anpolimus commented on modules/openy_gc_log/src/LogArchiver.php
> +        if ($entity) {
@hamrant I've updated it according to php standard
previous was producing fatal error:)

2021-01-14 16:19 UTC, hamrant commented
@froboy please fix to

```php
use Drupal\Core\Entity\EntityInterface;

...

        if (!$entity instanceof EntityInterface) {
          continue;
        }
```

And make force push to remove the commit from @anpolimus

2021-01-14 16:40 UTC, hamrant submitted a review, later dismissed

2021-01-14 16:42 UTC, podarok approved these changes

2021-01-14 16:49 UTC, podarok submitted a review, later dismissed

2021-01-15 10:04 UTC, hamrant approved these changes

2021-01-15 17:01 UTC, NadyaRudenko commented
Tested, no error occurs while I export logs. 
But in the exported logs the viewed live stream that I changed is not present. I don't know if this is expected behavior, so want a confirmation. Thanks!
![image](https://user-images.githubusercontent.com/62060358/104755780-91893800-5763-11eb-8bd2-01ce3f391a0c.png)
![image](https://user-images.githubusercontent.com/62060358/104756079-fa70b000-5763-11eb-993d-9da5aa303cca.png)

2021-01-19 12:53 UTC, anpolimus commented
retest

2021-01-19 14:59 UTC, NadyaRudenko commented
retest

2021-01-19 17:12 UTC, merged