Styles for top menu with alerts
fivejars/openy_gated_content pull request #243
Opened 2021-01-20 09:18 UTC by retif

**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-158

## Steps to test:

- [ ] Add alert
- [ ] Open VY homepage
- [ ] Check that alerts displayed correctly
- [ ] Check that admin menu displayed correctly

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

2021-01-20 09:22 UTC, hamrant approved these changes
Code looks ok

2021-01-20 10:29 UTC, anpolimus requested changes

2021-01-20 10:29 UTC, anpolimus commented on assets/js/alerts.behaviors.js
> +            if ($('#openy_alerts_app_header .slick-slide').length > 0) {
We need to follow one way.
If you want to get rid of jquery like in the code above, let's avoid jquery code here as well

2021-01-20 10:29 UTC, anpolimus commented on assets/js/alerts.behaviors.js
> +              console.log('add alerts class to body');
Let's skip console.log. It is good to have it during development, but after that, it will clog console output.

2021-01-20 10:29 UTC, anpolimus commented on assets/js/alerts.behaviors.js
> +              console.log('remove alerts class from body');
the same

2021-01-20 10:34 UTC, anpolimus commented
Issue has gone for a regular user but in case of admin there is small issue during scrolling:
![image](https://user-images.githubusercontent.com/3023950/105162839-cc042380-5b1b-11eb-8821-405ee996f4e3.png)

2021-01-20 14:17 UTC, retif commented
retest

2021-01-20 16:01 UTC, NadyaRudenko commented
Tested on Chrome and iPhone
1. Alert is hidden on Rose and Lily on Schedule page on desktop
![image](https://user-images.githubusercontent.com/62060358/105199307-501fd080-5b47-11eb-8c2a-0c9c690b38f8.png)
2. On mobile on Rose and Lily on the Schedule page alert is partly hidden
![image](https://user-images.githubusercontent.com/62060358/105200431-7eea7680-5b48-11eb-9a5b-f27248242995.png)
![image](https://user-images.githubusercontent.com/62060358/105200504-91fd4680-5b48-11eb-93d6-ae5ae2b03b6a.png)
3. On desktop and mobile on the Schedule page for Carnation alert covers week's dates and there is a spacing between alert and content
![image](https://user-images.githubusercontent.com/62060358/105200084-1dc2a300-5b48-11eb-994f-d0f67c4b67e9.png)
![image](https://user-images.githubusercontent.com/62060358/105200208-42b71600-5b48-11eb-9d87-ba7f21d1585a.png)
4. As an admin on Carnation you can see spacing under and above the alert on all pages
![image](https://user-images.githubusercontent.com/62060358/105200997-0afc9e00-5b49-11eb-9a9a-aea5529103d2.png)
5. As an admin on Lily you can see that both menus got cropped a little, but still you can access all links. not critical
![image](https://user-images.githubusercontent.com/62060358/105201279-5d3dbf00-5b49-11eb-89c7-89247e698c3b.png)

2021-01-22 16:23 UTC, NadyaRudenko approved these changes
retested, all fixed apart from the big spacing on the admin view on Carnation, but I think we can leave it, it doesn't block other functionality
![image](https://user-images.githubusercontent.com/62060358/105516695-da4e6d00-5cde-11eb-9c65-e081ea4dceb2.png)

2021-01-22 17:55 UTC, anpolimus approved these changes

2021-01-22 18:14 UTC, merged