Proddev 123
fivejars/openy_gated_content pull request #244
Opened 2021-01-20 17:26 UTC by NightHunterSV

https://openy.atlassian.net/browse/PRODDEV-123

## Steps to test:

- [ ] Log in as an admin
- [ ] Ensure the Open Y Virtual YMCA Log module is enabled
- [ ] Navigate through the site, start the video playback, etc.
- [ ] Go to the Logs view page and ensure there are data about your activity duration
![image](https://user-images.githubusercontent.com/5138333/105209963-1bb21180-5b53-11eb-9ea4-7658578a2048.png)

- [ ] Set the least value in the VY log module settings for the Activity granularity interval
![image](https://user-images.githubusercontent.com/5138333/105210724-173a2880-5b54-11eb-8e6b-8bdec283d552.png)

- [ ] Be inactive during this time
- [ ] Start navigating, playing video, etc. after the interval gone
- [ ] Ensure there is another log record, gathering the activity time for the user
![image](https://user-images.githubusercontent.com/5138333/105211744-4c934600-5b55-11eb-9d25-27512569dbee.png)

- [ ] Export logs and ensure the data about an activity are present in the resulting file
![image](https://user-images.githubusercontent.com/5138333/105211874-6d5b9b80-5b55-11eb-8521-85498a10764f.png)

2021-01-21 09:00 UTC, NightHunterSV commented
retest

2021-01-21 10:12 UTC, hamrant requested changes

2021-01-21 11:04 UTC, hamrant commented
@NightHunterSV please increase items number on views to 50:

![Screenshot from 2021-01-21 13-03-07](https://user-images.githubusercontent.com/13733670/105342495-1a332880-5be9-11eb-8a4a-466c7a66ecfa.png)

2021-01-21 13:20 UTC, anpolimus requested changes

2021-01-21 13:20 UTC, anpolimus commented on modules/openy_gc_log/src/Field/PayloadFieldItemList.php
> +    $this->dateFormatter = \Drupal::service('date.formatter');
Why not to use DI here?

2021-01-21 13:20 UTC, anpolimus commented
retest

2021-01-25 15:10 UTC, NightHunterSV commented
retest

2021-01-25 16:27 UTC, hamrant commented
@NightHunterSV please set  `Activity granularity interval` default value to 15 mins

2021-01-28 15:01 UTC, hamrant requested changes
Tested, works fine. @NightHunterSV please fix route permission and we can merge this

2021-01-29 17:59 UTC, anpolimus approved these changes

2021-02-02 15:30 UTC, hamrant approved these changes

2021-02-04 10:01 UTC, AnastasiiaPys commented
Tested, all good. Thanks.

2021-02-04 10:12 UTC, merged