ReClique SSO Integration in openy_gc_auth_reclique_oauth2 module
fivejars/openy_gated_content pull request #254
Opened 2021-01-28 12:16 UTC by retif

**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-139

## Steps to test:

- [ ] Enable openy_gc_auth_reclique_oauth2 module
- [ ] Enter Reclique credentials at Reclique OAuth2 provider settings
- [ ] Enable Reclique OAuth2 provider
- [ ] Try to login at Virtual Y

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

2021-01-29 10:02 UTC, hamrant commented
The current code looks ok for me.

2021-01-29 15:06 UTC, anpolimus requested changes
For better naming convention, lets rename it to openy_gc_auth_reclique_sso

2021-01-29 15:12 UTC, anpolimus requested changes

2021-01-29 15:12 UTC, anpolimus commented on modules/openy_gc_auth/modules/openy_gc_auth_reclique_oauth2/src/Client.php
> +   * @TODO fix
If it was fixed, do we need to delete this?

2021-01-29 15:12 UTC, anpolimus commented on modules/openy_gc_auth/modules/openy_gc_auth_reclique_oauth2/src/Plugin/GCIdentityProvider/RecliqueOAuth2.php
> +      'login_mode' => 'present_login_button',
lets add `authorization_server` => `https://[association_slug].recliquecore.com`

2021-01-29 15:44 UTC, NadyaRudenko commented
when you log out from Virtual Y, you remain logged in ReClique https://monosnap.com/file/V3g1spPqLyl8dwKkHifD3jnohVwPbu
@retif , @anpolimus

2021-01-29 15:49 UTC, retif commented
> when you log out from Virtual Y, you remain logged in ReClique https://monosnap.com/file/V3g1spPqLyl8dwKkHifD3jnohVwPbu
> @retif , @anpolimus

I think that is okay

2021-01-29 17:07 UTC, anpolimus commented
@NadyaRudenko Oleks is right.
In the scope of this task, log out from CRM is not included.

2021-01-29 17:13 UTC, NadyaRudenko approved these changes

2021-01-29 17:49 UTC, anpolimus commented on modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/OAuth2Client.php
> +class OAuth2Client {
We also have to rename it to RecliqueClient for better readability

2021-02-01 09:13 UTC, anpolimus approved these changes

2021-02-01 09:24 UTC, anpolimus commented
Code is ok.
Tested at build - everything is working properly.

2021-02-01 09:24 UTC, merged

2021-04-07 19:03 UTC, TomScarboroughYMCA commented
@NadyaRudenko - is there a way I can securely get a hold of the Client Id and Client Secret needed to test against the Open Y team's staging account with ReClique?

2021-04-07 19:28 UTC, NadyaRudenko commented
@anpolimus, please advise ^^^ thanks!

2021-04-12 16:47 UTC, TomScarboroughYMCA commented
@anpolimus and @NadyaRudenko - I was able to acquire some test credentials and do my testing, so I'm all-good on that. Hopefully you will see this so you will not get distracted getting me additional test users. Thanks again!