[PRODDEV-179] Store references entities' info in the metadata field, …
fivejars/openy_gated_content pull request #260
Opened 2021-02-04 15:19 UTC by NightHunterSV

…and use this info if the entity is not there already

https://openy.atlassian.net/browse/PRODDEV-179

## Steps to test:

- [ ] Log in as an admin
- [ ] Enable "Open Y Virtual YMCA Log" module
- [ ] Navigate through the site
- [ ] In the incognito browser mode or another browser log in as a common VY user
- [ ] Navigate through the site again
- [ ] Ensure the logs are displayed on the /admin/virtual-y-logs page
![image](https://user-images.githubusercontent.com/5138333/106913217-6fecf200-670c-11eb-941b-94ea4bf52aa9.png)

- [ ] Export the logs
- [ ] Ensure all the info is there
- [ ] Remove the dummy user you've used to navigate through the VY
- [ ] Ensure the logs are still available -- just the user's email is no more clickable
![image](https://user-images.githubusercontent.com/5138333/106913429-a62a7180-670c-11eb-9621-46981d1caceb.png)

- [ ] Export the logs and ensure the resulting file coincides with the previously exported
- [ ] Remove some of the entities you've looked, when surfed around the VY
- [ ] Ensure the logs are still available and contain the entities titles and instructor name of the removed entity
- [ ] Export the logs and ensure the resulting file coincides with the previously exported

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- [ ] This PR  provides updates to support the upgrade path
- [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

2021-02-04 17:52 UTC, anpolimus requested changes

2021-02-04 17:52 UTC, anpolimus commented on modules/openy_gc_log/openy_gc_log.install
> +  // Update entity to add the changed field.
I think it is better to separate views update and field install.
Not required, but if you have time, better for reading.

2021-02-04 17:52 UTC, anpolimus commented on modules/openy_gc_log/src/Entity/LogEntity.php
> +      ->setSetting('max_length', 255)
let's make it larger in case if we need to put more info to the meta in the future.

2021-02-05 10:20 UTC, anpolimus approved these changes

2021-02-05 12:17 UTC, AnastasiiaPys commented
Tested, all good now!

2021-02-05 12:52 UTC, hamrant approved these changes

2021-02-05 14:12 UTC, anpolimus commented on modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
> +          content: 'Below are this month''s logs. Older log entries can be found in the <a href=/admin/content/files?filename=virtual-y&filemime=application/x-gzip>Log Archives</a>.'
```suggestion
          content: '<div class="messages messages--warning">Below are this month's logs. Older log entries can be found in the <a href=/admin/content/files?filename=virtual-y&filemime=application/x-gzip>Log Archives</a>.</div>'
```

2021-02-05 14:22 UTC, anpolimus commented on modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
> +          content: '<div class="messages messages--warning">Below are this month's logs. Older log entries can be found in the <a href=/admin/content/files?filename=virtual-y&filemime=application/x-g
```suggestion
          content: '<div class="messages messages--warning">Below are this month\'s logs. Older log entries can be found in the <a href=/admin/content/files?filename=virtual-y&filemime=application/x-gzip>Log Archives</a>.</div>'
```

2021-02-05 14:37 UTC, anpolimus commented on modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
> +          content: '<div class="messages messages--warning">Below are this month\'s logs. Older log entries can be found in the <a href=/admin/content/files?filename=virtual-y&filemime=application/x-
```suggestion
          content: '<div class="messages messages--warning">Below are this months logs. Older log entries can be found in the <a href=/admin/content/files?filename=virtual-y&filemime=application/x-gzip>Log Archives</a>.</div>'
```

2021-02-05 14:55 UTC, merged