[PRODDEV-219] Implement redirect after login
fivejars/openy_gated_content pull request #289
Opened 2021-03-09 09:46 UTC by NightHunterSV

**Related Issue/Ticket:**
https://openy.atlassian.net/browse/PRODDEV-219

## Steps to test:

- [ ] Visit site as an anonymous
- [ ] Navigate through the site using the main navigation, for example
![image](https://user-images.githubusercontent.com/5138333/110451311-beefc380-80cc-11eb-987f-99153bf6524d.png)

- [ ] You should be redirected to the login page
![image](https://user-images.githubusercontent.com/5138333/110451387-d333c080-80cc-11eb-8834-49419fe201be.png)

- [ ] Log in
- [ ] Ensure you've been redirected to the needed location after the login
![image](https://user-images.githubusercontent.com/5138333/110451525-f199bc00-80cc-11eb-884f-5ca5644c7c45.png)

- [ ] Change the auth provider and ensure it is also working

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

2021-03-09 13:28 UTC, hamrant requested changes
@NightHunterSV let's rename some things in PR

2021-03-09 13:28 UTC, hamrant commented on js/gated-content/src/main.js
> +    const cookieName = 'Drupal_visitor_gc_auth_destination';
Let's rename `Drupal_visitor_gc_auth_destination` to `openy_gc_auth_destination`

2021-03-09 13:28 UTC, hamrant commented on modules/openy_gc_auth/js/auth.behaviors.js
> +     $.cookie('Drupal_visitor_gc_auth_destination', window.location.hash);
Let's rename `Drupal_visitor_gc_auth_destination` to `openy_gc_auth_destination`

2021-03-09 13:28 UTC, hamrant commented on modules/openy_gc_auth/openy_gc_auth.libraries.yml
> +auth:
Let's rename library name `auth` to `auth_destination`

2021-03-09 13:28 UTC, hamrant commented on modules/openy_gc_auth/src/Plugin/Block/VirtualYLoginBlock.php
> +    $form['#attached']['library'][] = 'openy_gc_auth/auth';
Let's rename library name `auth` to `auth_destination`

2021-03-11 13:26 UTC, hamrant approved these changes

2021-03-11 14:33 UTC, AnastasiiaPys commented
Tested for dummy, reclique, y-usa providers. Testing passed.

2021-03-11 15:40 UTC, anpolimus approved these changes

2021-03-11 15:52 UTC, merged