Personal Training
fivejars/openy_gated_content pull request #307
Opened 2021-04-08 11:04 UTC by retif

**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-192

## Steps to test:

- [ ] Enable openy_gc_personal_training module
- [ ] Create personal training in admin panel
- [ ] Open personal training page

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

2021-04-08 12:06 UTC, anpolimus approved these changes

2021-04-08 13:42 UTC, hamrant commented
retest

2021-04-09 09:53 UTC, hamrant requested changes

2021-04-09 09:53 UTC, hamrant commented on js/gated-content/src/views/PersonalTrainingPage.vue
> +          console.log(this.video);
Please remove `console.log`

2021-04-12 12:43 UTC, hamrant commented on js/gated-content/src/views/PersonalTrainingPage.vue
> -            <AddToCalendar :event="event"></AddToCalendar>
@NightHunterSV please note, `AddToCalendar` was removed

2021-04-12 12:43 UTC, hamrant approved these changes

2021-04-13 10:39 UTC, retif commented
retest

2021-04-13 11:24 UTC, merged