[PRODDEV-349] Implement audio status indication component. Make video…
fivejars/openy_gated_content pull request #348
Opened 2021-06-03 11:00 UTC by NightHunterSV

… status more noticeable

**Related Issue/Ticket:**

https://openy.atlassian.net/browse/PRODDEV-349

## Steps to test:

- [ ] Log in to VY as an admin
- [ ] Enable PTs module
- [ ] Add Virtual trainer role for admin
- [ ] Open site in another browser / anonymous mode
- [ ] Log in as a user
- [ ] As an admin, create PT and reference self at the `Trainer` field, newly created user -- as a `Customer`
- [ ] From the VY dashboard, navigate to the PT you've created
- [ ] Join the meeting
- [ ] Verify there is a sound indicator, and its size depends on the input volume:

![image](https://user-images.githubusercontent.com/5138333/120634258-b7457e00-c473-11eb-8cec-b8dcbd0b6c2e.png)

- [ ] Verify the microphone and video disabled states are reflected in the indicators:

![image](https://user-images.githubusercontent.com/5138333/120634504-fd9add00-c473-11eb-8925-605e4cdbae02.png)

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

2021-06-03 11:34 UTC, anpolimus commented on js/gated-content/src/store/modules/personalTraining/webrtc/mediaStream.js
> +      }349
```suggestion
      }
```

2021-06-03 11:41 UTC, anpolimus requested changes

2021-06-03 11:41 UTC, anpolimus commented on js/gated-content/src/components/personal-training/meeting/MeetingPlayer.vue
> +      <div class="video-state-indicator">
Since, we've created Audio indicator above, we can easily develop small component for video indicator and put it everywhere on the app.

2021-06-03 13:24 UTC, gianni-imagex commented
https://openy.atlassian.net/browse/PRODDEV-349

2021-06-04 10:16 UTC, podarok approved these changes

2021-06-07 08:15 UTC, hamrant approved these changes

2021-06-07 08:47 UTC, AnastasiiaPys commented
retest

2021-06-17 12:08 UTC, AnastasiiaPys commented
retest

2021-06-17 13:57 UTC, AnastasiiaPys commented
Tested on macOs (chrome, safari), Windows 10( Edge), Iphone 11( Safari), Ipad Air 4( Safari)
- The instructor's indicators are not visible when horizontal view is on on the Iphone
![image](https://user-images.githubusercontent.com/76169576/122409678-fe5f6300-cf8b-11eb-94d6-2e401d8c8e68.png)
- The instructor's mic indicator is not visible when horizontal view is on on the Ipad
![image](https://user-images.githubusercontent.com/76169576/122409891-2cdd3e00-cf8c-11eb-88cd-0c336ffad2f0.png)

2021-06-24 15:11 UTC, NightHunterSV commented
Closing in favor to https://github.com/fivejars/openy_gated_content/pull/354

2021-06-24 15:11 UTC, closed without merging