[PRODDEV-414] New Admin for Virtual Y Homepage
fivejars/openy_gated_content pull request #384
Opened 2021-09-03 15:56 UTC by Sardis93

**Related Issue/Ticket:**

[PRODDEV-414](https://openy.atlassian.net/browse/PRODDEV-414)

## Steps to test:

- [ ] Visit Virtual Y settings page, accessible via toolbar "**Virtual Y**" -> "**Virtual YMCA settings**".
- [ ] Confirm **Switch to Legacy View** checkbox replaces **Components Settings** with **Legacy View** fieldset.
- [ ] Confirm that any field for new components (within **Components Settings**) can be updated correctly.

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [x] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [x] This change does not contain front-end fixes.
- [x] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

2021-09-03 17:01 UTC, anpolimus approved these changes

2021-09-06 11:55 UTC, anpolimus approved these changes

2021-09-06 12:35 UTC, hamrant requested changes

2021-09-06 12:35 UTC, hamrant commented on src/Form/GCSettingsForm.php
> +      '#description' => $this->t('Legacy View has the following components: Virtual Y Video, Live streams, Virtual meetings, Blog posts.'),
Legacy View has the following components `on the Home page`: Virtual Y Video, Live streams, Virtual meetings, Blog posts.

2021-09-06 12:35 UTC, hamrant commented on src/Form/GCSettingsForm.php
> +    $this->prepareLegacyView($form, $config);
```php
    $this->prepareComponents($form, $config);
    $this->prepareLegacyView($form, $config);
```

These functions are very similar. I think we can simplify this and avoid copy/past. Let's add an additional argument `array $components` and maybe container_id and merge to one function

2021-09-08 14:24 UTC, hamrant commented on src/Form/GCSettingsForm.php
> +    $this->prepareLegacyView($form, $config);
We with @Sardis93 decided to rollback to the previous version, so let's resolve this conversation

2021-09-08 14:47 UTC, hamrant approved these changes

2021-09-13 16:30 UTC, AnastasiiaPys commented
retest

2021-09-13 17:04 UTC, AnastasiiaPys commented
Tested on macOS(Chrome).
Works as expected.

2021-09-13 17:04 UTC, merged