[PRODDEV-479] Flag new shared content
fivejars/openy_gated_content pull request #423
Opened 2021-12-06 23:15 UTC by froboy

Do not merge PR, only review it and approve/request changes.
Merge is allowed by QA Engineer only.

**Related Issue/Ticket:**

**PLEASE CHECK BASE BRANCH FOR YOUR PR**
**ONLY urgent and approved fixes for point release should go to master branch**

https://openy.atlassian.net/browse/PRODDEV-479

WIP
- [x] Add "date added column"
- [x] Bold rows when they're new
- [ ] Unbold rows when they've been viewed

## Steps to test:

- [ ] First do this
- [ ] Then do this (and look at this great screenshot).
- [ ] Finally observe the issue is resolved.

## Quality checks:

Please check these boxes to confirm this PR covers the following cases:

- Maintaining our upgrade path is essential. Check one or the other:
  - [ ] This PR  provides updates via `hook_update_N` or other means.
  - [ ] No updates are necessary for this change.
- Front end fixes should be tested against all of the Open Y Themes.
  - [ ] Tested against Carnation
  - [ ] Tested against Lily
  - [ ] Tested against Rose
  - [ ] This change does not contain front-end fixes.
- [ ] I have flagged this PR "Needs Review" or pinged the VY devs/QA
  team in Slack

2021-12-08 18:13 UTC, froboy commented
@anpolimus I've completed refactoring based on our call this morning. This is now ready for review again.

2021-12-08 18:14 UTC, froboy commented
retest

2021-12-08 20:50 UTC, AndreyMaximov commented
retest

2021-12-09 14:52 UTC, anpolimus requested changes

2021-12-09 14:52 UTC, anpolimus commented on modules/openy_gc_shared_content/src/Form/SharedContentPreviewForm.php
> +    $form['#attached']['library'][] = 'core/drupal.ajax';
there is no need to do that. Drupal addsa drupal.ajax to the each form itself.
```suggestion
    
```

2021-12-09 14:59 UTC, froboy commented on modules/openy_gc_shared_content/src/Form/SharedContentPreviewForm.php
> +    // Group submit handlers in an actions element with a key of "actions" so
```suggestion
    // Group submit handlers in an actions element with a key of "actions" so
```

2021-12-10 16:49 UTC, AnastasiiaPys commented
Tested. Works as expected.
1.Shared Content is flagged as new by formatting the row with “bold text”
2.After user clicked the Preview button, the row looks unbolded
3.Content updated on the server since user (Admin) last visit is flagged as “new” by formatting the row with *bold text*.
4.After the content was fetched to the site, the button “Preview” changed to the “Added”.

But an error occurred  after I added new content to the server and fetched the content again. 
![image](https://user-images.githubusercontent.com/76169576/145608288-0065781b-4e63-4112-95b8-4cc6028344d1.png)

@froboy is this the type of error that is preventing me from merging this build? or can i merge the build?

2021-12-10 16:54 UTC, froboy commented
@AnastasiiaPys comparing the filename in the first line of the error to the files changed here I can see that the error is definitely a result of my new code, so we should resolve that and retest. I'll get on it. Thanks!

2021-12-10 17:31 UTC, froboy commented
@AnastasiiaPys I believe I've resolved that issue. Please retest when you're able. Thanks!

2021-12-14 15:29 UTC, anpolimus approved these changes

2021-12-14 15:38 UTC, merged