Rearch: Close password reset and login form for virtual_y roles
fivejars/openy_gated_content pull request #98
Opened 2020-09-08 09:53 UTC by jediandrey

2020-09-10 11:01 UTC, anpolimus commented on openy_gated_content.module
> +    \Drupal::messenger()->addError('You\'re not allowing to reset password for user with Virtual Y role.');
```suggestion
    \Drupal::messenger()->addError('You\'re not allowed to reset password since you're Virtual Y user.');
```

2020-09-10 11:01 UTC, anpolimus commented on openy_gated_content.module
> +    \Drupal::messenger()->addError('You\'re not allowing to login with Virtual Y user role.');
```suggestion
    \Drupal::messenger()->addError('You\'re not allowed to login since you are Virtual Y user.');
```

2020-09-10 11:26 UTC, anpolimus commented
retest

2020-09-10 11:37 UTC, anpolimus requested changes

2020-09-10 11:37 UTC, anpolimus commented on openy_gated_content.module
> +  if ($account && $account->hasRole('virtual_y_user')) {
@jediandrey there will be many different virtual Y roles, that could be changed from project to project.
Our agreement that we have to check virtual_y_* (all roles that starts with virtual_y)

2020-09-14 08:42 UTC, hamrant commented
retest

2020-09-14 08:44 UTC, hamrant submitted a review, later dismissed

2020-09-14 09:06 UTC, anpolimus commented on openy_gated_content.module
> +      if (strpos($role, 'virtual_y')) {
```suggestion
      if (strpos($role, 'virtual_y_')) {
```

2020-09-14 09:07 UTC, anpolimus commented on openy_gated_content.module
> +      if (strpos($role, 'virtual_y')) {
@jediandrey @hamrant we have Virtual Y editor role that will be blocked without my fix above ^^
![image](https://user-images.githubusercontent.com/3023950/93066581-d6507580-f682-11ea-8b9c-10fb4cb22270.png)

2020-09-14 10:17 UTC, anpolimus commented
Works as expected.
Merging.

2020-09-14 10:17 UTC, anpolimus approved these changes

2020-09-14 10:17 UTC, merged